version: '3'

services:
  webapp:
    container_name: website_prod
    env_file:
      - ../apps/website/.env.production
    build:
      context: ../
      dockerfile: apps/website/Dockerfile
    restart: always
    ports:
      - 5010:3000
